apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  my-pvc
spec:
  volumeName: my-nfs-pv
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

