    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: test-dynamic-volume-claim
    spec:
      storageClassName: "nfs-csi"
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 100Mi
